POST http://localhost:8080/usermanagement-1.0-SNAPSHOT/api/hello-world/register
Content-Type: application/json

{
  "firstname": "testvorname",
  "lastname": "testnachname",
  "username": "aoeu",
  "password": "aoeu"
}

<> 2021-11-26T193402.200.txt
<> 2021-11-26T193132.200.txt
<> 2021-11-26T192819.400.html

###
###
GET http://localhost:8080/usermanagement-1.0-SNAPSHOT/api/hello-world/login
Content-Type: application/json

{
  "username": "aoeu",
  "password": "aoeu"
}

###
###
GET http://localhost:8080/usermanagement-1.0-SNAPSHOT/api/hello-world/isSessionActive
sessionId: fd83f1c0-7516-47da-92a7-c6801350e545
